language: php

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  except:
  - /^feature\/[-\w]+$/

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - WP_VERSION=4.6.12 WP_MULTISITE=0
  - WP_VERSION=4.7.11 WP_MULTISITE=0
  - WP_VERSION=4.8.7 WP_MULTISITE=0
  - WP_VERSION=4.9.8 WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

stages:
  - validate
  - test

jobs:
  include:
  - stage: validate
    name: "Basic Checks"
    php: 7.2
    before_install:
      - phpenv config-rm xdebug.ini
      - composer require bartlett/php-compatinfo:5.* --dev
      - composer require phpunit/phpunit:5.7.* --dev
    before_script: skip
    script: ./vendor/bin/phpunit -c phpunit-checks.xml --no-coverage
  - stage: validate
    name: 'Minimum requirement'
    env: WP_VERSION=4.6.0 WP_MULTISITE=0
    php: '5.3'
    dist: precise
    before_install:
      - phpenv config-rm xdebug.ini
      - composer require phpunit/phpunit:4.8.* --dev
  - stage: validate
    name: 'Latest versions'
    env: WP_VERSION=4.9.8 WP_MULTISITE=0
    php: '7.2'
    before_install: composer require phpunit/phpunit:5.7.* --dev
    before_script:
      - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    script: ./vendor/bin/phpunit
    after_script:
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

matrix:
  exclude:
    - env: WP_VERSION=nightly WP_MULTISITE=0
      php: '5.6'
    - env: WP_VERSION=nightly WP_MULTISITE=0
      php: '7.0'
    - env: WP_VERSION=nightly WP_MULTISITE=0
      php: '7.1'
  allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer require phpunit/phpunit:5.7.* --dev
install: composer install --prefer-source
before_script: bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: ./vendor/bin/phpunit --no-coverage
