language: php

notifications:
  email:
    on_success: never
    on_failure: always

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - WP_VERSION=4.6.11 WP_MULTISITE=0
  - WP_VERSION=4.7.10 WP_MULTISITE=0
  - WP_VERSION=4.8.6 WP_MULTISITE=0
  - WP_VERSION=4.9.6 WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

matrix:
  allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install --prefer-source

after_script:
  - CODECLIMATE_REPO_TOKEN=c0e18ea554a37a7495947a34c818939c0599bde7c1efa3ee136989c053dde9da ./vendor/bin/test-reporter
